## Student Performance Analysis With Linear Algebra

## 1 . Analysis 2. Exercises

In [154]:
import numpy as np

### 1. Analysis

 #### 3.1 Representing Data as a matrix

$$
Scores = \begin{bmatrix}
80 & 70 & 90 \\
60 & 85 & 75 \\
95 & 88 & 92 \\
70 & 60 & 65 
\end{bmatrix}





In [155]:
scores = np.array([[80,70,90],[60,85,75],[95,88,92],[70,60,65]])
student1_scores = np.array([80,70,90])
student2_scores = np.array([60,85,75])
student3_scores = np.array([95,88,92])
student4_scores = np.array([70,60,65])
print(scores)

[[80 70 90]
 [60 85 75]
 [95 88 92]
 [70 60 65]]


#### 3.2 Total Scores per Student (Vector Addition)

student 1 = [80 + 70 + 90] = 240
<br>

student 2 = [60 + 85 + 75] = 220
<br>

student 3 = [95 + 88 + 92] = 275
<br>

student 4 = [70 + 60 + 65] = 195

In [156]:
student1_scores.sum()
print(f"Student 1 total score is {student1_scores.sum()}")

Student 1 total score is 240


In [157]:
student2_scores.sum()
print(f"Student 2 total score is {student2_scores.sum()}")

Student 2 total score is 220


In [158]:
student3_scores.sum()
print(f"Student 3 total score is {student3_scores.sum()}")

Student 3 total score is 275


In [159]:
student4_scores.sum()
print(f"Student 4 total score is {student1_scores.sum()}")

Student 4 total score is 240


#### 3.3 Aplying Weights (Scalar Multiplication)
Maths_scalar = 2
<br>
English_scalar = 1.5
<br>
Science_scalar = 1
<br>

Maths_weight = 2(Math_scores)

$$
Maths Weight = \begin{bmatrix}
160 \\
120 \\
190 \\
140 \\
\end{bmatrix}


In [160]:
scalar_weight = [2,1.5,1]
Maths_weight = scalar_weight[0] * scores[:,0]
print("Mathematics Weight :",Maths_weight)

Mathematics Weight : [160 120 190 140]



English_weight = 2(English_scores)

$$
English Weight = \begin{bmatrix}
105 \\
127.5 \\
132 \\
90 \\
\end{bmatrix}

In [161]:
English_weight = scalar_weight[1] * scores[:,1]
print("English Language Weight :",English_weight)

English Language Weight : [105.  127.5 132.   90. ]



Science_weight = 1(Science_scores)

$$
Science Weight = \begin{bmatrix}
90 \\
75 \\
92 \\
65 \\
\end{bmatrix}

In [162]:
Science_weight = scalar_weight[2] * scores[:,2]
print("Science Weight :",Science_weight)

Science Weight : [90 75 92 65]


#### 3.4 Average Score per Subject (Matrix Operations)

Maths_Average = (80 + 60 + 95 + 70)/4 = 305/4 = 76.25
<br>

English_Average = (70 + 85 + 88 + 60)/4 = 303/4 = 75.75
<br>

Science_Average = (90 + 75 + 92 + 65) = 322/4 = 80.5

In [163]:
# Average Score per Students

Scores_per_subject = np.mean(scores,axis = 0)
scoress = ['Maths','English','Science']
b = 1
for scoress,st in zip(scoress,Scores_per_subject):
    print(f"Average {scoress} scores : {st}")
    b+=1

Average Maths scores : 76.25
Average English scores : 75.75
Average Science scores : 80.5


#### 3.5 Final Grades using Matrix Multiplication

weight_vector = [0.5 , 0.3 ,0.2]

Math_final_grades :
$$
0.5*Maths_Scores = \begin{bmatrix}
40 \\
30 \\
47.5 \\
35
\end{bmatrix}




In [164]:
# Math fnal grades 
scalar_math = 0.5
Math_final_grades = scalar_math * scores[:,0]
print(f"Mathematics Final grades : \n{Math_final_grades.reshape(4,1)}")

Mathematics Final grades : 
[[40. ]
 [30. ]
 [47.5]
 [35. ]]




English_final_grades :
$$
0.3*English_Scores = \begin{bmatrix}
21 \\
25.5 \\
26.4 \\
18
\end{bmatrix}


In [165]:
# English fnal grades 
scalar_english = 0.3
English_final_grades = scalar_english * scores[:,1]
print(f"English Final grades : \n{English_final_grades.reshape(4,1)}")

English Final grades : 
[[21. ]
 [25.5]
 [26.4]
 [18. ]]



Science_final_grades :
$$
0.2*Science_Scores = \begin{bmatrix}
18 \\
15 \\
18.4 \\
13
\end{bmatrix}


In [166]:
# Science fnal grades 
scalar_science = 0.2
Science_final_grades = scalar_science * scores[:,2]
print(f"Science Final grades : \n{Science_final_grades.reshape(4,1)}")

Science Final grades : 
[[18. ]
 [15. ]
 [18.4]
 [13. ]]


#### 3.6 Comparing Students (Vector Subtraction)
student1_Math_score = 80
<br>

student1_English_score = 70
<br>

Student1_scores = [80 + 70 + 90] = 240
<br>


student2_Math_score = 60
<br>

student2_English_score = 85
<br>

Student2_scores = [60 + 85 + 75] = 220
<br>


student1_Math_score - student2_Math_score = 80 - 60 = 20
<br>

#### Student1 performed better in Mathematics than student 2
<br>

student1_Eglish_score - student2_English_score = 70 - 85 = -15
<br>

#### Student2 performed better in English Language than student 1
<br>


student1_Science_score - student2_Science_score = 90 - 75 = 15
<br>

#### Student1 performed better in Science than student 2
<br>


Overall :
<br>

Student1_scores = [80 + 70 + 90] = 240  -   Student2_scores = [60 + 85 + 75] = 220
<br>

### Student 1 performed better overall than Student 2

In [167]:
Math_compared = scores[0,0] - scores[1,0]
print(f"Student 1 performed better than Student 2 in Mathematics with a difference of {Math_compared}")

Student 1 performed better than Student 2 in Mathematics with a difference of 20


In [168]:
English_compared = scores[0,1] - scores[1,1]
print(f"Student 2 performed better than Student 1 in Engish with a difference of 15")


Student 2 performed better than Student 1 in Engish with a difference of 15


In [169]:
Science_compared = scores[0,2] - scores[1,2]
print(f"Student 1 performed better than Student 2 in Science with a difference of {Science_compared}")

Student 1 performed better than Student 2 in Science with a difference of 15


In [170]:
studen1_overall_scores = np.sum(scores[0])

student2_overall_scores = np.sum(scores[1])

student_overall_compared = studen1_overall_scores - student2_overall_scores

print(f"Student 1 performed better overall than Student 2 with an overall difference of {student_overall_compared}")

Student 1 performed better overall than Student 2 with an overall difference of 20


### Add-on Exercises

#### Exercise 1. 
$$
Scores = \begin{bmatrix}
80 & 70 & 90 & 50 \\
60 & 85 & 75 & 60 \\
95 & 88 & 92 & 70 \\
70 & 60 & 65 & 80 \\
70 & 55 & 75 & 60 


\end{bmatrix}

In [189]:
scores = np.array([[80,70,90,50],[60,85,75,60],[95,88,92,70],[70,60,65,80],[70,55,75,60]])
student1_scores = np.array([80,70,90,50])
student2_scores = np.array([60,85,75,60])
student3_scores = np.array([95,88,92,70])
student4_scores = np.array([70,60,65,80])
student5_scores = np.array([70,55,75,60])
print(scores)

[[80 70 90 50]
 [60 85 75 60]
 [95 88 92 70]
 [70 60 65 80]
 [70 55 75 60]]


#### 3.2 Total Scores per Student (Vector Addition)

student 1 = [80 + 70 + 90 + 50] = 290
<br>

student 2 = [60 + 85 + 75 + 60] = 280
<br>

student 3 = [95 + 88 + 92 + 70] = 345
<br>

student 4 = [70 + 60 + 65 + 80] = 275
<br>

student 5 = [70 + 55 + 75 + 60] = 260

In [190]:
student1_scores.sum()
print(f"Student 1 total score is {student1_scores.sum()}")

Student 1 total score is 290


In [191]:
student2_scores.sum()
print(f"Student 2 total score is {student2_scores.sum()}")

Student 2 total score is 280


In [192]:
student3_scores.sum()
print(f"Student 3 total score is {student3_scores.sum()}")

Student 3 total score is 345


In [193]:
student4_scores.sum()
print(f"Student 4 total score is {student4_scores.sum()}")

Student 4 total score is 275


In [194]:
student5_scores.sum()
print(f"Student 4 total score is {student5_scores.sum()}")

Student 4 total score is 260


#### 3.4 Average Score per Subject (Matrix Operations)

Maths_Average = (80 + 60 + 95 + 70 + 70)/5 = 375/5 = 75
<br>

English_Average = (70 + 85 + 88 + 60 + 55)/5 = 358/5 = 71.6
<br>

Science_Average = (90 + 75 + 92 + 65 + 75)/5 = 397/5 = 79.4
<br>

Physics_Average = (50 + 60 + 70 + 80 + 60)/5 = 320/5 = 64

In [195]:
# Average Score per Students

Scores_per_subject = np.mean(scores,axis = 0)
scoress = ['Maths','English','Science','Physics']
b = 1
for scoress,st in zip(scoress,Scores_per_subject):
    print(f"Average {scoress} scores : {st}")
    b+=1

Average Maths scores : 75.0
Average English scores : 71.6
Average Science scores : 79.4
Average Physics scores : 64.0


#### Exercise 2. 
Maths_scalar = 3
<br>
English_scalar = 1
<br>
Science_scalar = 1
<br>

Maths_weight = 3(Math_scores)

$$
Maths Weight = \begin{bmatrix}
240 \\
180 \\
285 \\
210 \\
210
\end{bmatrix}





Scores with Maths Weight 



$$
Scores with MathsWeight = \begin{bmatrix}
240 & 70 & 90 & 50 \\
180 & 85 & 75 & 60 \\
285 & 88 & 92 & 70 \\
210 & 60 & 65 & 80 \\
210 & 55 & 75 & 60 


\end{bmatrix}

In [196]:
scalar_weight = [3,1,1]
Maths_weight = scalar_weight[0] * scores[:,0]
print("Mathematics Weight :",Maths_weight)

Mathematics Weight : [240 180 285 210 210]


In [197]:
new_scores = scores.copy()
print(new_scores)

[[80 70 90 50]
 [60 85 75 60]
 [95 88 92 70]
 [70 60 65 80]
 [70 55 75 60]]


In [198]:
new_scores[:,0] = Maths_weight
print(f"The new scores : \n{new_scores}")

The new scores : 
[[240  70  90  50]
 [180  85  75  60]
 [285  88  92  70]
 [210  60  65  80]
 [210  55  75  60]]


#### Exercise 3. 
weight_vector = [0.4 , 0.2 ,0.3,0.1]

Math_final_grades :
$$
0.4*Maths_Scores = \begin{bmatrix}
32 \\
24 \\
38 \\
28 \\
28
\end{bmatrix}


In [199]:
# Math fnal grades 
scalar_math = 0.4
Math_final_grades = scalar_math * scores[:,0]
print(f"Mathematics Final grades : \n{Math_final_grades.reshape(5,1)}")

Mathematics Final grades : 
[[32.]
 [24.]
 [38.]
 [28.]
 [28.]]




English_final_grades :
$$
0.2*English_Scores = \begin{bmatrix}
14 \\
17 \\
17.6 \\
12 \\
11
\end{bmatrix}


In [200]:
# English fnal grades 
scalar_english = 0.2
English_final_grades = scalar_english * scores[:,1]
print(f"English Final grades : \n{English_final_grades.reshape(5,1)}")

English Final grades : 
[[14. ]
 [17. ]
 [17.6]
 [12. ]
 [11. ]]


Science_final_grades :
$$
0.3*Science_Scores = \begin{bmatrix}
27 \\
22.5 \\
27.6 \\
19.5 \\
22.5
\end{bmatrix}


In [201]:
# Science fnal grades 
scalar_science = 0.3
Science_final_grades = scalar_science * scores[:,2]
print(f"Science Final grades : \n{Science_final_grades.reshape(5,1)}")

Science Final grades : 
[[27. ]
 [22.5]
 [27.6]
 [19.5]
 [22.5]]


Physics_final_grades :
$$
0.1*Science_Scores = \begin{bmatrix}
5 \\
6 \\
7 \\
8 \\
6
\end{bmatrix}


In [202]:
# Physics final grades 
scalar_physics = 0.1
physics_final_grades = scalar_physics * scores[:,3]
print(f"Physics Final grades : \n{physics_final_grades.reshape(5,1)}")

Physics Final grades : 
[[5.]
 [6.]
 [7.]
 [8.]
 [6.]]


In [203]:
math_grades = np.array([[32.],
                        [24.],
                        [38.],
                        [28.],
                        [28.]])


english_grades = np.array([[14. ],
                           [17. ],
                           [17.6],
                           [12. ],
                           [11. ]])




science_grades = np.array([[27. ],
                           [22.5],
                           [27.6],
                           [19.5],
                           [22.5]])


physics_grades = np.array([[5.],
                           [6.],
                           [7.],
                           [8.],
                           [6.]])



final_grades_matrix = np.hstack((math_grades, english_grades, science_grades, physics_grades))

print(final_grades_matrix)

[[32.  14.  27.   5. ]
 [24.  17.  22.5  6. ]
 [38.  17.6 27.6  7. ]
 [28.  12.  19.5  8. ]
 [28.  11.  22.5  6. ]]


#### Exercise 4

Matrix slice (rows 2–3, all columns):

Student 3 = [95, 88, 92, 70]
<br>
Student 4 = [70, 60, 65, 80]

Difference (Student4 – Student3):
= [70-95, 60-88, 65-92, 80-70]
= [-25, -28, -27, 10]

Interpretation:

Negative = Student 3 performed better.
Positive = Student 4 performed better.
So:

Maths: Student 3 better by 25
English: Student 3 better by 28
Science: Student 3 better by 27
Computer: Student 4 better by 10

In [204]:
student3_and_4 = scores[2:4, :]
print(f"Scores of Student 3 and 4 only: \n {student3_and_4}")
diff_matrix = np.diff(student3_and_4, axis=0)
print(f"\nComparing Student 3 and 4 Scores(By Subject): \n{diff_matrix}")

i=0
for diff in diff_matrix[0]:
    if diff < 0:
        print(f"Student 3 performed better in Subject {i+1} by {abs(diff)} marks")
    else: 
        print(f"Student 4 performed better in Subject {i+1} by {abs(diff)} marks")
        
    i+=1

Scores of Student 3 and 4 only: 
 [[95 88 92 70]
 [70 60 65 80]]

Comparing Student 3 and 4 Scores(By Subject): 
[[-25 -28 -27  10]]
Student 3 performed better in Subject 1 by 25 marks
Student 3 performed better in Subject 2 by 28 marks
Student 3 performed better in Subject 3 by 27 marks
Student 4 performed better in Subject 4 by 10 marks
