# Question 1

Matrix A is a (2 by 3) matrix

Matrix B is a (3 by 2) matrix

# Question 2

The matrices can  be multiplied, this is so because the number of columns of matrix A is same as the number of rows of matrix B. It can be multiplied in both (AB),(BA) format.

In [ ]:
import numpy as np
np.set_printoptions(precision=3, suppress=True)

matrixA= np.array([[2,-1,3],[0,4,1]])

matrixB=np.array([[1,2],[-2,0],[5,-3]])

matrixAB=matrixA.dot(matrixB)
print("Multiplying matrix A and B will give\n",matrixAB)

matrixBA=matrixB.dot(matrixA)
print("Multiplying matrix B and A will give\n",matrixBA)


Multiplying matrix A and B will give
 [[19 -5]
 [-3 -3]]
Multiplying matrix A and B will give
 [[  2   7   5]
 [ -4   2  -6]
 [ 10 -17  12]]
